Algoritmo "AT24"


Var
a:inteiro


Inicio
escreval("Informe a idade")
leia(a)
se (a >= 5) e (a <= 7)entao
escreval("Infantil A")
senao
se (a >= 8) e (a <= 10) entao
escreval("Infantil B")
senao
se (a >= 11) e (a <= 13) entao
escreval("Juvenil A")
senao
se (a >= 14) e (a <= 17) entao
escreval("Juvenil B")
senao
se (a >= 18) e (a <= 25) entao
escreval("Sênior")
senao
escreva("Idade fora de faxia etária")
fimse
fimse
fimse
fimse
fimse


Fimalgoritmo